### ISSUE TITLE
Add wildcard entries to security rules

### ISSUE THREAD

**Issue by YourTechBud** [spacecloud-io/space-cloud#192]
Thats a great question!! If i understand this question, you want to prevent the client from updating certain columns?

Assuming that's the case and the field / column you want to protect is named `protectMe`, you can have a `match` rule something like this:
```yaml
rules:
  update:
    rule: match
    eval: ==
    type: bool
    f1: utils.exist(args.update.$set.protectMe)
    f2: false
```

the solution above is not documented I guess. The `utils.exist()` function seems to be a well kept secret. @Jayesh333 we should get that done

This will protect you against all `set` operations. The client still be able to unset it. Thats a security threat. Normally you wouldn't wanna keep protected data in a collection/table which the user has access to. Can you keep it in a separate table where only an `admin` role or the backend functions can access it? This is what we do. A lil more about your use case would help me give a more accurate answer.

@Jayesh333 another better way of solving this would be introducing wildcards to rules. So basically the new rule would look like this:

> **Note:** this is a proposal and the code below hasn't been implemented

```yaml
rules:
  update:
    rule: match
    eval: ==
    type: bool
    f1: utils.exist(args.update.*.protectMe)
    f2: false
```
The above config would prevent any kind of update whatsoever!

_Originally posted by @YourTechBud in https://github.com/spaceuptech/space-cloud/issues/146#issuecomment-483479359_
